name: user-timeline-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  image: library/mongo
  imageVersion: 4.4.6
  name: user-timeline-mongodb
  ports: 
  - containerPort: 27017
  rcpu: 1000m
  rmemory: 500Mi
  lcpu: 1500m

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod