name: user-timeline-redis

ports:
  - port: 6379
    targetPort: 6379

container:
  args: 
  - /social-network-microservices/config/redis.conf
  image: library/redis
  imageVersion: 6.2.4 
  name: user-timeline-redis
  ports: 
  - containerPort: 6379

configMaps:
  - name: redis.conf
    mountPath: /social-network-microservices/config/redis.conf
    value: redis

rcpu: 800m
rmemory: 800Mi
lcpu: 800m
lmemory: 800Mi
replicas: 7
minReplicas: 7